'use strict';

module.exports = {
  OK:                    'OK',
  CREATED:               'Created',
  UPDATED:               'Updated',
  DELETED:               'Deleted',
  VALIDATION_FAILED:     'Validation failed',
  NOT_FOUND:             'Not found',
  INTERNAL_ERROR:        'Internal server error',

  AUTH_REQUIRED:         'Authentication required',
  AUTH_INVALID:          'Invalid credentials',
  AUTH_2FA_REQUIRED:     'Two-factor authentication required',
  AUTH_2FA_INVALID:      'Invalid verification code',
  AUTH_LOGGED_OUT:       'Logged out',
  AUTH_TOO_MANY:         'Too many attempts. Try again later.',
  AUTH_PANEL_DENIED:     'Access denied for this panel',
  AUTH_INSTITUTION_SUSPENDED: 'This institution is currently unavailable',
  AUTH_SCOPE_VIOLATION:  'Access denied',
  AUTH_TOKEN_EXPIRED:    'Session expired. Please log in again.',
  AUTH_TOKEN_INVALID:    'Invalid session. Please log in again.',
  OPERATOR_2FA_MANDATORY:'Two-factor authentication is mandatory for operators',

  INST_CREATED:          'Institution created',
  INST_UPDATED:          'Institution updated',
  INST_SUSPENDED:        'Institution suspended',
  INST_REACTIVATED:      'Institution reactivated',
  INST_TERMINATED:       'Institution terminated',
  INST_GRANT_ADMIN:      'Admin access granted',
  INST_REVOKE_ADMIN:     'Admin access revoked',
  INST_IMPERSONATE:      'Impersonation session started',
  INST_NOT_FOUND:        'Institution not found',
  INST_NO_OWNER:         'Institution has no owner teacher',
  INST_NOT_AVAILABLE:    'This institution is currently unavailable',
  RENT_INVOICE_NOT_FOUND:'Rent invoice not found',
  RENT_MARKED_PAID:      'Rent invoice marked paid',

  TEACHER_CREATED:       'Teacher created',
  TEACHER_UPDATED:       'Teacher updated',
  TEACHER_NOT_FOUND:     'Teacher not found',
  TEACHER_BELONGS_ELSEWHERE: 'That teacher already belongs to another institution',
  STUDENT_CREATED:       'Student created',
  STUDENT_UPDATED:       'Student updated',
  STUDENT_NOT_FOUND:     'Student not found',
  STUDENT_BAD_REFS:      'Teacher, batch or instrument is invalid for this institution',
  BATCH_CREATED:         'Batch created',
  BATCH_UPDATED:         'Batch updated',
  REQUEST_CREATED:       'Request submitted',
  REQUEST_APPROVED:      'Request approved',
  REQUEST_REJECTED:      'Request rejected',
  REQUEST_NOT_FOUND:     'Request not found',
  REQUEST_NOT_PENDING:   'Request is no longer pending',
  TEACHER_PANEL_ACCESS_FORBIDDEN: 'Admin cannot set panel access or ownership',
  BATCH_NOT_FOUND:       'Batch not found',
  BATCH_BAD_REFS:        'Instrument, day pattern, time slot or teacher is invalid for this institution',
  DAY_PATTERN_DUPLICATE: 'That day pattern already exists',
  TIME_SLOT_DUPLICATE:   'That time slot already exists',
  TIME_SLOT_RANGE_INVALID: 'End time must be after start time',

  HOLIDAY_DECLARED:      'Holiday declared',
  SESSION_LAUNCHED:      'Session launched',
  SESSION_NOT_FOUND:     'Session not found',
  BRANDING_UPDATED:      'School profile updated',
  BRANDING_INVALID:      'Invalid branding values',
  UPLOAD_NOT_CONFIGURED: 'File uploads are not configured on this server',
  SLUG_REQUEST_CREATED:  'Slug change requested — your platform administrator will review it',
  SLUG_REQUEST_INVALID:  'That slug is not valid',
  SLUG_REQUEST_TAKEN:    'That slug is not available',
  SLUG_REQUEST_PENDING:  'A slug change request is already pending',
  SLUG_REQUEST_NOT_FOUND:'Slug change request not found',
  SLUG_REQUEST_HANDLED:  'Request is no longer pending',
  SLUG_REQUEST_APPROVED: 'Slug change approved',
  SLUG_REQUEST_REJECTED: 'Slug change rejected',

  ACTIONS: {
    CREATE_INSTITUTION:    'CREATE_INSTITUTION',
    UPDATE_INSTITUTION:    'UPDATE_INSTITUTION',
    TOGGLE_MODE:           'TOGGLE_MODE',
    SUSPEND_INSTITUTION:   'SUSPEND_INSTITUTION',
    REACTIVATE_INSTITUTION:'REACTIVATE_INSTITUTION',
    TERMINATE_INSTITUTION: 'TERMINATE_INSTITUTION',
    GRANT_ADMIN:           'GRANT_ADMIN',
    REVOKE_ADMIN:          'REVOKE_ADMIN',
    IMPERSONATE_START:     'IMPERSONATE_START',
    MARK_RENT_PAID:        'MARK_RENT_PAID',
    CREATE_STUDENT:        'CREATE_STUDENT',
    UPDATE_STUDENT:        'UPDATE_STUDENT',
    UPDATE_PAID_AMOUNT:    'UPDATE_PAID_AMOUNT',
    CREATE_TEACHER:        'CREATE_TEACHER',
    UPDATE_TEACHER:        'UPDATE_TEACHER',
    CREATE_BATCH:          'CREATE_BATCH',
    UPDATE_BATCH:          'UPDATE_BATCH',
    CREATE_REQUEST:        'CREATE_REQUEST',
    APPROVE_REQUEST:       'APPROVE_REQUEST',
    REJECT_REQUEST:        'REJECT_REQUEST',
    CREATE_PAYMENT:        'CREATE_PAYMENT',
    CREATE_DAY_PATTERN:    'CREATE_DAY_PATTERN',
    UPDATE_DAY_PATTERN:    'UPDATE_DAY_PATTERN',
    CREATE_TIME_SLOT:      'CREATE_TIME_SLOT',
    UPDATE_TIME_SLOT:      'UPDATE_TIME_SLOT',
    CREATE_HOLIDAY:        'CREATE_HOLIDAY',
    DELETE_HOLIDAY:        'DELETE_HOLIDAY',
    LAUNCH_SESSION:        'LAUNCH_SESSION',
    UPDATE_BRANDING:       'UPDATE_BRANDING',
    REQUEST_SLUG_CHANGE:   'REQUEST_SLUG_CHANGE',
    APPROVE_SLUG_CHANGE:   'APPROVE_SLUG_CHANGE',
    REJECT_SLUG_CHANGE:    'REJECT_SLUG_CHANGE',
    MARK_ATTENDANCE:       'MARK_ATTENDANCE',
    ADVANCE_STUDENT_STATUS:'ADVANCE_STUDENT_STATUS',
    EXPIRE_VALIDITY:       'EXPIRE_VALIDITY',
  },
};
